---
title: "R Notebook"
output: html_notebook
---

```{r}

library(tidyverse)
library(skimr)



# create book data

book_data <- read.csv("data/books.csv")

```

# Now to get some basic info about the data

```{r}

# How much data are we looking at?
dim(book_data)
# 11134 Objects over 13 Variables.?

names(book_data)
view(book_data)
skim(book_data)
sum(is.na(book_data)) # Check for how many NA values are in the dataset

book_data %>% 
  summarise(across(.fns = ~ sum(is.na(.x)))) # breakdown the number of NA's in dataset by column

# Drop any NA values

book_data <- book_data %>%
  mutate(authors = na_if(authors,"NOT A BOOK")) %>% #Added this line after running top10 check
  drop_na()
  

# Running this showed no change in number of objects, either no NA's or values are classed differently
  

# # Creating a variable to store data with the relevant columns we will be using
# 
book_data_sm <- book_data %>%
  select(title, authors, average_rating, language_code, publisher, num_pages, text_reviews_count)
  

# 

# #create a variable with the top 10 best rated books
# 
top10_books <- book_data_sm %>%
  select(title, authors, average_rating) %>%
  arrange(desc(average_rating)) %>%
  slice_head(n = 10)

top10_books

# Checking this identified "NOT A BOOK" author name, need to remove for better answer
# 
# 
# # find out top 10 books that aren't native english language 


#remove any english variants from the data set, using count function to check remaining values

top10_noneng <- book_data_sm %>% 
  filter(
    language_code != "eng" & 
      language_code != "en-GB" & 
      language_code != "en-US" & 
      language_code != "enm" & 
      language_code != "en-CA"
    ) %>% 
  # count(language_code) # this was used to check what options remained, commented out once all english options were removed
  select(title, authors, average_rating, language_code) %>% 
  arrange(desc(average_rating)) %>% 
  slice_head(n = 10)

top10_noneng

# no similarities between the top books in english and non english. 
# Going to compare if we remove the 5 star rating from english books if we get any non english entries for top 10

book_data_sm %>% 
  filter(average_rating != 5.00) %>% 
  arrange(desc(average_rating))


# Removing 5 star books, we have one German book that makes it into the top 10

# Lets see what author has written the most pages

most_pages_by_author <- book_data_sm %>% 
  select(authors, num_pages) %>%
  # After running once, Anonymous is included, should be removed
  filter(authors != "Anonymous") %>% 
  separate(col = authors, into = c("primary_author", "supporting_authors"), sep = "/") %>% 
  group_by(authors) %>% 
  summarise(total_pages = sum(num_pages)) %>% 
  arrange(desc(total_pages)) %>% 
  slice_head(n = 10)

# Correct way from notes in class

book_data %>%
  select(authors, num_pages) %>%
  # will cover separate this afternoon :) 
  separate(col = authors, into = c("primary_author", "supporting_authors_illustrators"), sep = "/",extra = "merge") %>% 
  # After running once, Anonymous is included, should be removed
  filter(primary_author != "Anonymous") %>%
  group_by(primary_author) %>%
  summarise(total_pages = sum(num_pages)) %>% 
  arrange(desc(total_pages)) %>%
  slice_head(n = 10)


# Which publisher gets the best ratings for their books on average

best_publishers <- book_data_sm %>%
  filter(average_rating != 0 & text_reviews_count > 50) %>% 
  select(publisher, average_rating) %>%
  group_by(publisher) %>% 
  summarise(average_rating = mean(average_rating)) %>% 
  arrange(desc(average_rating)) %>% 
  slice_head(n = 10)

# this first version is biased due to multiple academic books being rated 5 without any actual ratings. 
# In order to make this more interesting, I will also filter out anything with less than 50 reviews
  

# Using the same method, see how the top 10 changes if review count matters



book_data_sm %>%
  filter(text_reviews_count > 50) %>% 
  select(title, authors, average_rating, text_reviews_count) %>%
  arrange(desc(average_rating)) %>%
  slice_head(n = 10)

# This proves that Calvin & Hobbes is the greatest piece of literature ever written. 


```

